version: "3.8"

services:
  wordpress:
    image: 'bitnami/wordpress'
    expose:
      - '8080'
    networks:
      - front-network
      - network-db
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DATABASE_HOST: 'mariadb'
      WORDPRESS_DATABASE_USER: 'exampleuser'
      WORDPRESS_DATABASE_PASSWORD: 'examplepass'
      WORDPRESS_DATABASE_NAME: 'exampledb'
    volumes:
      - wordpress_data:/bitnami/wordpress

  proxy:
    image: 'nginx:latest'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on: 
      - wordpress
    networks:
      - front-network

  mariadb:
    image: 'mariadb:latest'
    environment:
      MYSQL_DATABASE: 'exampledb'
      MYSQL_USER: 'exampleuser'
      MYSQL_PASSWORD: 'examplepass'
      MYSQL_ROOT_PASSWORD: 'aze+123'
    networks:
      - network-db
    volumes:
      - mariadb_data:/bitnami/mariadb

networks:
  front-network:
    driver: bridge
  network-db:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:
